#Include "Protheus.ch"
//-----------------------------------------------------------------------
/*/{Protheus.doc} M020INC()

Ponto de entrada na inclusão de fornecedores
@param		Nenhum
@return		Nenhum
@author 	Zema
@since 		26/07/2016
@version 	1.0
@project	MAN0000001 - Aguassanta - Integra
/*/
//-----------------------------------------------------------------------
User Function M020INC

// Gera o cadastro de itens contábeis com o CNPJ do fornecedor / cliente
U_ASCTBA11("SA2")

Return
