#INCLUDE 'PROTHEUS.CH'
#INCLUDE 'PARMTYPE.CH'

//-----------------------------------------------------------------------
/*/{Protheus.doc} SACI008                     
Ponto de Entrada na Baixa de Contas a Receber - Integração TIN
@param		Nenhum
@return		Nenhum
@author 	Zema
@since 		08/09/2017
@version 	1.0
@project	MAN0000001 - Aguassanta - Integra
/*/
//-----------------------------------------------------------------------
USER FUNCTION SACI008
U_ASTIN025()        
U_ASTIN033()
RETURN