#IFDEF SPANISH
         #define STR0001  "Emite una relacion con los itemes en stock que llegaron al punto de"
         #define STR0002  "pedido, sugiriendo la cantidad a comprar."
         #define STR0003  "A Rayas"
         #define STR0004  "Administracion"
         #define STR0005  "Itemes en Punto de Pedido"
         #define STR0006  "PRODUCTO(S)"
         #define STR0007  "CODIGO          DESCRIPCION                    TP GRP  UM SALDO ACTUAL     PUNTO DE     STOCK DE         LOTE ___TOLERANCIA___     CANTIDAD   CANTIDAD A   VALOR ESTIMADO BASE FECHA DE   VALOR UNITARIO     PLAZO DE"
         #define STR0008  "                                                                             PEDIDO    SEGUIRDAD    ECONOMICO   %     CANTIDAD   POR EMBAL.      COMPRAR     DE LA COMPRA      REFERENCIA   DE LA COMPRA      ENTREGA"
         #define STR0009  "ANULADO POR EL OPERADOR"
         #define STR0010  "TOTAL GENERAL A COMPRAR"
		 #define STR0011  "Dia(s)"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Prints a list of Inventory items that have reached the Point of"
         #define STR0002  "Order, suggesting the quantity to purchase"
         #define STR0003  "Z.Form "
         #define STR0004  "Management   "
         #define STR0005  "Items in Point of Order"
         #define STR0006  "PRODUCT(S)"
         #define STR0007  "CODE            DESCRIPT.                      TP GRP  UM  CURR.BALANCE   POINT OF      SECURITY      ECONOMIC___TOLERANCE ___   QUANTITY    QUANTITY TO   VALUE  ESTIMAT BASE  DATE OF   UNIT VALUE OF      DELIVERY"
         #define STR0008  "                                                                             ORDER         STOCK          LOT  %      QUANTITY   PER PACK.      PURCHASE      OF PURCHASE       REFERENC       PURCHASE          TERM"
         #define STR0009  "CANCELLED BY OPERATOR  "
         #define STR0010  "TOTAL TO PURCHASE"
		 #define STR0011  "Day(s)"
   #ELSE
         #define STR0001  "Emite uma relacao com os itens em estoque que atingiram o Ponto de"
         #define STR0002  "Pedido ,sugerimdo a quantidade a comprar."
         #define STR0003  "Zebrado"
         #define STR0004  "Administracao"
         #define STR0005  "Itens em Ponto de Pedido"
         #define STR0006  "PRODUTO(S)"
         #define STR0007  "CODIGO          DESCRICAO                      TP GRP  UM  SALDO ATUAL     PONTO DE   ESTOQUE DE         LOTE ___TOLERANCIA___   QUANTIDADE QUANTIDADE A   VALOR ESTIMADO BASE  DATA DE   VALOR UNITARIO     PRAZO DE"
         #define STR0008  "                                                                             PEDIDO    SEGURANCA    ECONOMICO   %   QUANTIDADE   POR EMBAL.      COMPRAR        DA COMPRA      REFERENCIA      DA COMPRA      ENTREGA"
         #define STR0009  "CANCELADO PELO OPERADOR"
         #define STR0010  "TOTAL GERAL A COMPRAR"
         #define STR0011  "Dia(s)"
   #ENDIF
#ENDIF