#IFDEF SPANISH
         #define STR0001  "Emision de la relacion de los pedidos de compras."
         #define STR0002  "Sera solicitada la orden y el intervalo para"
         #define STR0003  "la emision de los pedidos de compras."
         #define STR0004  " Por Numero         "
         #define STR0005  " Por Producto       "
         #define STR0006  " Por Proveedor    "
         #define STR0007  "Relacion de pedidos de compras"
         #define STR0008  "A Rayas"
         #define STR0009  "Administracion"
         #define STR0010  "RELACION DE PEDIDOS DE COMPRAS"
         #define STR0011  "RELACION DE LOS PEDIDOS DE COMPRAS"
         #define STR0012  "AUTOR. Num: "
         #define STR0013  "PEDIDO Num: "
         #define STR0014  " - POR NUMERO"
         #define STR0015  "IT CODIGO          DESCRIPCION                    CR   CODIGO  RAZON SOCIAL                       FCH. DE  ENTREGA    CANTIDADE  UM         VALOR           VALOR     VALOR TOTAL   CANT.       CANT. A        SALDO   RES."
         #define STR0016  "  PRODUCTO         DE PRODUCTO                         PROVE.                                     EMISION  PREVISTA       PEDIDA            UNIT.         IMPUESTO    CON IMPUESTO  ENTREGA.    RECIBIR        RECIBIR ELIM."
         #define STR0017  "PRODUCTO: "
         #define STR0018  " - POR PRODUCTO"
         #define STR0019  "PEDIDO ITEM  FECHA        CODIGO RAZON SOCIAL                         TELEFONO    ENTREGA           CANTIDAD           VALOR      DESCONTO         VALOR     PRECIO TOTAL       CANTIDAD      CANTIDAD       SALDO RESIDUOS"
         #define STR0020  "             EMISION      PROVEE.                                     PROVEE.     PREVISTA            PEDIDA        UNITARIO                         IMP      CON IMPUESTO        ENTREG.    A RECIBIR      COBRAR ELIMINADO"
         #define STR0021  "PROVEEDOR  : "
         #define STR0022  " - POR PROVEEDOR "
         #define STR0023  "PEDIDO ITEM  FECHA    CODIGO           DESCRIPCION DEL PRODUCTO   GRUPO  ENTREGA           CANTIDAD          PRECIO       DESCONTO        VALOR     PRECIO TOTAL     CANTIDAD    CANTIDAD       SALDO   RESIDUOS"
         #define STR0024  "NUMERO       EMISION  PRODUCTO                                           PREVISTA            PEDIDA        UNITARIO                     IMPUESTO     CON IMPUESTO      ENTREG.   A RECIBIR      COBRAR  ELIMINADOS"
         #define STR0025  ", Todos"
         #define STR0026  ", En Abierto"
         #define STR0027  ", Residuos"
         #define STR0028  ", Atendidos"
         #define STR0029  "ANULADO POR EL OPERADOR"
         #define STR0030  "PEDIDOS"
         #define STR0031  'No'
         #define STR0032  'Si'
         #define STR0033  "Total General"
         #define STR0034  "Total de los Itemes"
         #define STR0035  "Total del Producto"
         #define STR0036  "Total del Proveedor "
         #define STR0037  "Valor Total.......: "
         #define STR0038  "Flete.............: "
         #define STR0039  "Descuento.........: "
         #define STR0040  "Total del Pedido..: "
         #define STR0041  "Telefono: "
         #define STR0042  "PED/AE ITEM  FECHA    CODIGO           DESCRIPCION DEL PRODUCTO       GRUPO  ENTREGA           CANTIDAD        PRECIO               VALOR      PRECIO TOTAL          CANTIDAD     CANTIDAD         SALDO   RESIDUOS"
         #define STR0043  "PED/AE ITEM  FECHA        CODIGO RAZON SOCIAL                            TELEFONO    ENTREGA          CANTIDAD        VALOR         VALOR      PRECIO TOTAL         CANTIDAD      CANTIDAD       SALDO     RESIDUOS"
         #define STR0044  " Fax: "
         #define STR0045  " Contacto: "
         #define STR0046	"IT CODIGO          DESCRIPCION                    GRP  CODIGO               RAZON SOCIAL          FCH. DE  ENTREGA   CANTIDAD    UM      VALOR        VALOR         VALOR TOTAL  CANT.       CANT. A           SALDO   RES."
         #define STR0047  "PEDIDO ITEM  FCH.      CODIGO               RAZON SOCIAL          FONE            ENTREGA         CANTIDAD             VALOR    DESCUENTO           VALOR     PRECIO TOTAL        CANTIDAD     CANT. A          SALDO RESIDUOS"		
         #define STR0048  "SOLICITUD DE COMPRAS NRO.:"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Report of Purchase Orders list"
         #define STR0002  "The Sort type and the Interval must be entered"
         #define STR0003  "in order to issue the Purchase Orders."
         #define STR0004  " By Number"
         #define STR0005  " By Product"
         #define STR0006  " By Supplier"
         #define STR0007  "List of Purchase Orders"
         #define STR0008  "Z.Form "
         #define STR0009  "Management"
         #define STR0010  "LIST OF PURCHASE ORDERS"
         #define STR0011  "LIST OF PURCHASE ORDERS"
         #define STR0012  "AUTHOR.NR.: "
         #define STR0013  "ORDER  NR.: "
         #define STR0014  " - BY NUMBER"
         #define STR0015  "IT PRODUCT         PRODUCT                        CR   SUPPL. CORPORATE NAME                      ISSUE    EXPECTED      QUANTITY  UM      VALUE            VALUE         TOTAL VALUE  QUANT.   QUANT.TO       RECEIVED CLEAR."
         #define STR0016  "   CODE            DESCRIPTION                          CODE                                      DATE     DELIV.DATE     ORDERED           UNIT.             IPI         (W/IPI)      DELIV.   RECEIVE        BALANCE  RES."
         #define STR0017  "PRODUCT : "
         #define STR0018  " - BY PRODUCT"
         #define STR0019  "ORDER  ITEM  ISSUE     SUPPL. CORPORATE NAME                      SUPPLIER        EXPECTED          QUANTITY            UNIT    DISCOUNT           VALUE     TOTAL VALUE        QUANTITY   QUANT.TO        BALANCE CLEAR."
         #define STR0020  "             DATE      CODE                                       PHONE           DELIVERY           ORDERED           VALUE                         IPI       (W/IPI)         DELIVERED    RECEIVE     RECEIVABLE RESIDUE"
         #define STR0021  "SUPPLIER   : "
         #define STR0022  " - BY SUPPLIER  "
         #define STR0023  "ORDER  ITEM  ISSUE   PRODUCT         PRODUCT DESCRIPTION            GROUP EXPECTED      QUANTITY              UNIT     DISCOUNT           VALUE    TOTAL PRICE       QUANTITY    QUANTITY        BALANCE   CLEARED"
         #define STR0024  "NUMBER       DATE    CODE                                                 DELIVERY      ORDERED              PRICE                          IPI      (W/IPI)        DELIVERED  RECEIVABLE     RECEIVABLE   RESIDUE"
         #define STR0025  ", All  "
         #define STR0026  ", Open    "
         #define STR0027  ", Residues"
         #define STR0028  ", Attended "
         #define STR0029  "CANCELLED BY THE OPERATOR"
         #define STR0030  "ORDERS "
         #define STR0031  "No "
         #define STR0032  "Yes"
         #define STR0033  "Amount"
         #define STR0034  "Total of Items "
         #define STR0035  "Total of Product"
         #define STR0036  "Total of Supplier  "
         #define STR0037  "Total Value.......:"
         #define STR0038  "Freight...........:"
         #define STR0039  "Discount..........:"
         #define STR0040  "Total of Order...:"
         #define STR0041  "Phone:"
         #define STR0042  "ORD/DA ITEM  DATE     CODE             PRODUCT DESCRIPTION            GROUP  DELIVERY       QUANTITY              PRICE            VALUE       TOTAL              QUANTITY        QUANT. TO      BALANCE   RESIDUE"
         #define STR0043  "ORD/DA ITEM  DATE         CODE      CORPORATE NAME                            DELIVERY        QUANTITY            VALUE             VALUE      TOTAL              QUANTITY        QUANT. A       BALANCE   RESIDUE"
         #define STR0044  " Fax: "
         #define STR0045  " Contact: "
         #define STR0046  "IT CODE            DESCRIPTION                    GRP  CODE                 CORPORATE NAME        DELIVERY DATE      QUANTITY    UM      VALUE        VALUE         TOTAL VALUE  QUANT.      QUANT. TO         RES. BALANCES"
         #define STR0047  "ORDER  ITEM  DATE      CODE                 COMPANY NAME          PHONE           DELIVERY        QUANTITY             VALUE    DISCOUNT           VALUE     T O T A L        QUANTITY     QUANT. TO         RES. BALANCES"  
         #define STR0048  "PURCHASE REQUISITION NR.:"  
   #ELSE
         #define STR0001  "Emissao da Relacao de  Pedidos de Compras."
         #define STR0002  "Sera solicitado em qual Ordem, qual o Intervalo para"
         #define STR0003  "a emissao dos pedidos de compras."
         #define STR0004  " Por Numero         "
         #define STR0005  " Por Produto        "
         #define STR0006  " Por Fornecedor   "
         #define STR0007  "Relacao de Pedidos de Compras"
         #define STR0008  "Zebrado"
         #define STR0009  "Administracao"
         #define STR0010  "RELACAO DE PEDIDOS DE COMPRAS"
         #define STR0011  "RELACAO DOS PEDIDOS DE COMPRAS"
         #define STR0012  "AUTOR. N. : "
         #define STR0013  "PEDIDO N. : "
         #define STR0014  " - POR NUMERO"
         #define STR0015  "IT CODIGO          DESCRICAO                      CR   FORNECEDOR                                 DATA DE  ENTREGA    QUANTIDADE UM         VALOR           VALOR     VALOR TOTAL   QUANT.      QUANT.A        SALDO   RES."
         #define STR0016  "   PRODUTO         DO PRODUTO                                                                     EMISSAO  PREVISTA       PEDIDA            UNIT.             IPI         (C/IPI)   ENTREGUE    RECEBER        RECEBER ELIM."
         #define STR0017  "PRODUTO : "
         #define STR0018  " - POR PRODUTO"
         #define STR0019  "PEDIDO ITEM  DATA      CODIGO RAZAO SOCIAL                        FONE            ENTREGA         QUANTIDADE           VALOR    DESCONTO           VALOR     PRECO TOTAL      QUANTIDADE   QUANT. A          SALDO RESIDUOS"
         #define STR0020  "             EMISSAO   FORN.                                      FORN.           PREVISTA            PEDIDA        UNITARIO                         IPI       (C/IPI)          ENTREGUE    RECEBER        RECEBER ELIMINADOS"
         #define STR0021  "FORNECEDOR : "
         #define STR0022  " - POR FORNECEDOR"
         #define STR0023  "PEDIDO ITEM  DATA    CODIGO          DESCRICAO DO PRODUTO           GRUPO ENTREGA       QUANTIDADE           PRECO     DESCONTO           VALOR    PRECO TOTAL     QUANTIDADE   QUANT. A           SALDO   RESIDUOS"
         #define STR0024  "NUMERO       EMISSAO PRODUTO                                              PREVISTA          PEDIDA        UNITARIO                          IPI      (C/IPI)         ENTREGUE    RECEBER         RECEBER   ELIMINADOS"
         #define STR0025  ", Todos"
         #define STR0026  ", Em Abertos"
         #define STR0027  ", Residuos"
         #define STR0028  ", Atendidos"
         #define STR0029  "CANCELADO PELO OPERADOR"
         #define STR0030  "PEDIDOS"
         #define STR0031  "Nao"
         #define STR0032  "Sim"
         #define STR0033  "Total Geral "
         #define STR0034  "Total dos Itens "
         #define STR0035  "Total do Produto"
         #define STR0036  "Total do Fornecedor"
         #define STR0037  "Valor Total.......:"
         #define STR0038  "Frete.............:"
         #define STR0039  "Desconto..........:"
         #define STR0040  "Total do Pedido...:"
         #define STR0041  "Fone.:"
		 #define STR0042  "PED/AE ITEM  DATA     CODIGO           DESCRICAO DO PRODUTO           GRUPO  ENTREGA        QUANTIDADE            PRECO            VALOR       PRECO TOTAL        QUANTIDADE      QUANT. A       SALDO     RESIDUOS"
		 #define STR0043  "PED/AE ITEM  DATA         CODIGO    RAZAO SOCIAL                              ENTREGA         QUANTIDADE          VALOR             VALOR      PRECO TOTAL        QUANTIDADE      QUANT. A       SALDO     RESIDUOS"
  		 #define STR0044  " Fax: "
         #define STR0045  " Contato: "
 	     #define STR0046	"IT CODIGO          DESCRICAO                      GRP  CODIGO               RAZAO SOCIAL          DATA DE  ENTREGA   QUANTIDADE  UM      VALOR        VALOR         VALOR TOTAL  QUANT.      QUANT. A          SALDO   RES."
         #define STR0047  "PEDIDO ITEM  DATA      CODIGO               RAZAO SOCIAL          FONE            ENTREGA         QUANTIDADE           VALOR    DESCONTO           VALOR     PRECO TOTAL      QUANTIDADE   QUANT. A          SALDO RESIDUOS"		
         #define STR0048  "SOLICITACAO DE COMPRAS N.:"  
   #ENDIF
#ENDIF