#IFDEF SPANISH
	#DEFINE STR0001 "ATUALIZAÇÃO DE DICIONÁRIOS E TABELAS"
	#DEFINE STR0002 "Esta rotina tem como função fazer  a atualização  dos dicionários do Sistema ( SX?/SIX )"
	#DEFINE STR0003 "Este processo deve ser executado em modo EXCLUSIVO, ou seja não podem haver outros"
	#DEFINE STR0004 "usuários  ou  jobs utilizando  o sistema.  É EXTREMAMENTE recomendavél  que  se  faça um"
	#DEFINE STR0005 "BACKUP  dos DICIONÁRIOS  e da  BASE DE DADOS antes desta atualização, para que caso "
	#DEFINE STR0006 "ocorram eventuais falhas, esse backup possa ser restaurado."
	#DEFINE STR0007 "Confirma a atualização dos dicionários ?"
	#DEFINE STR0008 "Atualizando"
	#DEFINE STR0009 "Aguarde, atualizando ..."
	#DEFINE STR0010 "Atualização Concluída."
	#DEFINE STR0011 "Atualização Realizada."
	#DEFINE STR0012 "Arquivos Texto"
	#DEFINE STR0013 "Atualização da empresa "
	#DEFINE STR0014 " não efetuada."
	#DEFINE STR0015 "Empresa : "
	#DEFINE STR0017 "Dicionário de índices"
	#DEFINE STR0018 "Dicionário de dados"
	#DEFINE STR0019 "Atualizando campos/índices"
	#DEFINE STR0020 "Ocorreu um erro desconhecido durante a atualização da tabela : "
	#DEFINE STR0021 ". Verifique a integridade do dicionário e da tabela."
	#DEFINE STR0022 "ATENÇÃO"
	#DEFINE STR0023 "Ocorreu um erro desconhecido durante a atualização da estrutura da tabela : "
	#DEFINE STR0032 "LOG DA ATUALIZAÇÃO DOS DICIONÁRIOS"
	#DEFINE STR0033 " Dados Ambiente"
	#DEFINE STR0034 " Empresa / Filial...: "
	#DEFINE STR0035 " Nome Empresa.......: "
	#DEFINE STR0036 " Nome Filial........: "
	#DEFINE STR0037 " DataBase...........: "
	#DEFINE STR0038 " Data / Hora Ínicio.: "
	#DEFINE STR0039 " Environment........: "
	#DEFINE STR0040 " StartPath..........: "
	#DEFINE STR0041 " RootPath...........: "
	#DEFINE STR0042 " Versão.............: "
	#DEFINE STR0043 " Usuário TOTVS .....: "
	#DEFINE STR0044 " Computer Name......: "
	#DEFINE STR0045 " Dados Thread"
	#DEFINE STR0046 " Usuário da Rede....: "
	#DEFINE STR0047 " Estação............: "
	#DEFINE STR0048 " Programa Inicial...: "
	#DEFINE STR0049 " Conexão............: "
	#DEFINE STR0050 " Data / Hora Final.: "
	#DEFINE STR0051 "Atualização concluida."
	#DEFINE STR0052 "Não foi possível a abertura da tabela "
	#DEFINE STR0053 "de empresas (SM0)."
	#DEFINE STR0054 "de empresas (SM0) de forma exclusiva."
	#DEFINE STR0055 "Ínicio da Atualização"
	#DEFINE STR0060 "Final da Atualização"
	#DEFINE STR0083 "Índice criado "
	#DEFINE STR0085 "Atualizando índices..."
	#DEFINE STR0117 "Tela para Múltiplas Seleções de Empresas/Filiais"
	#DEFINE STR0118 "Selecione a(s) Empresa(s) para Atualização"
	#DEFINE STR0119 "Empresa"
	#DEFINE STR0120 "Todos"
	#DEFINE STR0121 "Marca / Desmarca"+ CRLF + "Todos"
	#DEFINE STR0122 "&Inverter"
	#DEFINE STR0123 "Inverter Seleção"
	#DEFINE STR0124 "Máscara Empresa ( ?? )"
	#DEFINE STR0125 "&Marcar"
	#DEFINE STR0126 "Marcar usando" + CRLF + "máscara ( ?? )"
	#DEFINE STR0127 "&Desmarcar"
	#DEFINE STR0128 "Desmarcar usando" + CRLF + "máscara ( ?? )"
	#DEFINE STR0143 "Chave do índice alterado "
	#DEFINE STR0145 "Confirma a seleção e efetua" + CRLF + "o processamento"
	#DEFINE STR0146 "Cancela o processamento" + CRLF + "e abandona a aplicação"
	#DEFINE STR0147 "Processar"
	#DEFINE STR0148 "Cancelar"
#ELSE
	#IFDEF ENGLISH
		#DEFINE STR0001 "ATUALIZAÇÃO DE DICIONÁRIOS E TABELAS"
		#DEFINE STR0002 "Esta rotina tem como função fazer  a atualização  dos dicionários do Sistema ( SX?/SIX )"
		#DEFINE STR0003 "Este processo deve ser executado em modo EXCLUSIVO, ou seja não podem haver outros"
		#DEFINE STR0004 "usuários  ou  jobs utilizando  o sistema.  É EXTREMAMENTE recomendavél  que  se  faça um"
		#DEFINE STR0005 "BACKUP  dos DICIONÁRIOS  e da  BASE DE DADOS antes desta atualização, para que caso "
		#DEFINE STR0006 "ocorram eventuais falhas, esse backup possa ser restaurado."
		#DEFINE STR0007 "Confirma a atualização dos dicionários ?"
		#DEFINE STR0008 "Atualizando"
		#DEFINE STR0009 "Aguarde, atualizando ..."
		#DEFINE STR0010 "Atualização Concluída."
		#DEFINE STR0011 "Atualização Realizada."
		#DEFINE STR0012 "Arquivos Texto"
		#DEFINE STR0013 "Atualização da empresa "
		#DEFINE STR0014 " não efetuada."
		#DEFINE STR0015 "Empresa : "
		#DEFINE STR0017 "Dicionário de índices"
		#DEFINE STR0018 "Dicionário de dados"
		#DEFINE STR0019 "Atualizando campos/índices"
		#DEFINE STR0020 "Ocorreu um erro desconhecido durante a atualização da tabela : "
		#DEFINE STR0021 ". Verifique a integridade do dicionário e da tabela."
		#DEFINE STR0022 "ATENÇÃO"
		#DEFINE STR0023 "Ocorreu um erro desconhecido durante a atualização da estrutura da tabela : "
		#DEFINE STR0032 "LOG DA ATUALIZAÇÃO DOS DICIONÁRIOS"
		#DEFINE STR0033 " Dados Ambiente"
		#DEFINE STR0034 " Empresa / Filial...: "
		#DEFINE STR0035 " Nome Empresa.......: "
		#DEFINE STR0036 " Nome Filial........: "
		#DEFINE STR0037 " DataBase...........: "
		#DEFINE STR0038 " Data / Hora Ínicio.: "
		#DEFINE STR0039 " Environment........: "
		#DEFINE STR0040 " StartPath..........: "
		#DEFINE STR0041 " RootPath...........: "
		#DEFINE STR0042 " Versão.............: "
		#DEFINE STR0043 " Usuário TOTVS .....: "
		#DEFINE STR0044 " Computer Name......: "
		#DEFINE STR0045 " Dados Thread"
		#DEFINE STR0046 " Usuário da Rede....: "
		#DEFINE STR0047 " Estação............: "
		#DEFINE STR0048 " Programa Inicial...: "
		#DEFINE STR0049 " Conexão............: "
		#DEFINE STR0050 " Data / Hora Final.: "
		#DEFINE STR0051 "Atualização concluida."
		#DEFINE STR0052 "Não foi possível a abertura da tabela "
		#DEFINE STR0053 "de empresas (SM0)."
		#DEFINE STR0054 "de empresas (SM0) de forma exclusiva."
		#DEFINE STR0055 "Ínicio da Atualização"
		#DEFINE STR0060 "Final da Atualização"
		#DEFINE STR0083 "Índice criado "
		#DEFINE STR0085 "Atualizando índices..."
		#DEFINE STR0117 "Tela para Múltiplas Seleções de Empresas/Filiais"
		#DEFINE STR0118 "Selecione a(s) Empresa(s) para Atualização"
		#DEFINE STR0119 "Empresa"
		#DEFINE STR0120 "Todos"
		#DEFINE STR0121 "Marca / Desmarca"+ CRLF + "Todos"
		#DEFINE STR0122 "&Inverter"
		#DEFINE STR0123 "Inverter Seleção"
		#DEFINE STR0124 "Máscara Empresa ( ?? )"
		#DEFINE STR0125 "&Marcar"
		#DEFINE STR0126 "Marcar usando" + CRLF + "máscara ( ?? )"
		#DEFINE STR0127 "&Desmarcar"
		#DEFINE STR0128 "Desmarcar usando" + CRLF + "máscara ( ?? )"
		#DEFINE STR0143 "Chave do índice alterado "
		#DEFINE STR0145 "Confirma a seleção e efetua" + CRLF + "o processamento"
		#DEFINE STR0146 "Cancela o processamento" + CRLF + "e abandona a aplicação"
		#DEFINE STR0147 "Processar"
		#DEFINE STR0148 "Cancelar"
	#ELSE
		#DEFINE STR0001 "ATUALIZAÇÃO DE DICIONÁRIOS E TABELAS"
		#DEFINE STR0002 "Esta rotina tem como função fazer  a atualização  dos dicionários do Sistema ( SX?/SIX )"
		#DEFINE STR0003 "Este processo deve ser executado em modo EXCLUSIVO, ou seja não podem haver outros"
		#DEFINE STR0004 "usuários  ou  jobs utilizando  o sistema.  É EXTREMAMENTE recomendavél  que  se  faça um"
		#DEFINE STR0005 "BACKUP  dos DICIONÁRIOS  e da  BASE DE DADOS antes desta atualização, para que caso "
		#DEFINE STR0006 "ocorram eventuais falhas, esse backup possa ser restaurado."
		#DEFINE STR0007 "Confirma a atualização dos dicionários ?"
		#DEFINE STR0008 "Atualizando"
		#DEFINE STR0009 "Aguarde, atualizando ..."
		#DEFINE STR0010 "Atualização Concluída."
		#DEFINE STR0011 "Atualização Realizada."
		#DEFINE STR0012 "Arquivos Texto"
		#DEFINE STR0013 "Atualização da empresa "
		#DEFINE STR0014 " não efetuada."
		#DEFINE STR0015 "Empresa : "
		#DEFINE STR0017 "Dicionário de índices"
		#DEFINE STR0018 "Dicionário de dados"
		#DEFINE STR0019 "Atualizando campos/índices"
		#DEFINE STR0020 "Ocorreu um erro desconhecido durante a atualização da tabela : "
		#DEFINE STR0021 ". Verifique a integridade do dicionário e da tabela."
		#DEFINE STR0022 "ATENÇÃO"
		#DEFINE STR0023 "Ocorreu um erro desconhecido durante a atualização da estrutura da tabela : "
		#DEFINE STR0032 "LOG DA ATUALIZAÇÃO DOS DICIONÁRIOS"
		#DEFINE STR0033 " Dados Ambiente"
		#DEFINE STR0034 " Empresa / Filial...: "
		#DEFINE STR0035 " Nome Empresa.......: "
		#DEFINE STR0036 " Nome Filial........: "
		#DEFINE STR0037 " DataBase...........: "
		#DEFINE STR0038 " Data / Hora Ínicio.: "
		#DEFINE STR0039 " Environment........: "
		#DEFINE STR0040 " StartPath..........: "
		#DEFINE STR0041 " RootPath...........: "
		#DEFINE STR0042 " Versão.............: "
		#DEFINE STR0043 " Usuário TOTVS .....: "
		#DEFINE STR0044 " Computer Name......: "
		#DEFINE STR0045 " Dados Thread"
		#DEFINE STR0046 " Usuário da Rede....: "
		#DEFINE STR0047 " Estação............: "
		#DEFINE STR0048 " Programa Inicial...: "
		#DEFINE STR0049 " Conexão............: "
		#DEFINE STR0050 " Data / Hora Final.: "
		#DEFINE STR0051 "Atualização concluida."
		#DEFINE STR0052 "Não foi possível a abertura da tabela "
		#DEFINE STR0053 "de empresas (SM0)."
		#DEFINE STR0054 "de empresas (SM0) de forma exclusiva."
		#DEFINE STR0055 "Ínicio da Atualização"
		#DEFINE STR0060 "Final da Atualização"
		#DEFINE STR0083 "Índice criado "
		#DEFINE STR0085 "Atualizando índices..."
		#DEFINE STR0117 "Tela para Múltiplas Seleções de Empresas/Filiais"
		#DEFINE STR0118 "Selecione a(s) Empresa(s) para Atualização"
		#DEFINE STR0119 "Empresa"
		#DEFINE STR0120 "Todos"
		#DEFINE STR0121 "Marca / Desmarca"+ CRLF + "Todos"
		#DEFINE STR0122 "&Inverter"
		#DEFINE STR0123 "Inverter Seleção"
		#DEFINE STR0124 "Máscara Empresa ( ?? )"
		#DEFINE STR0125 "&Marcar"
		#DEFINE STR0126 "Marcar usando" + CRLF + "máscara ( ?? )"
		#DEFINE STR0127 "&Desmarcar"
		#DEFINE STR0128 "Desmarcar usando" + CRLF + "máscara ( ?? )"
		#DEFINE STR0143 "Chave do índice alterado "
		#DEFINE STR0145 "Confirma a seleção e efetua" + CRLF + "o processamento"
		#DEFINE STR0146 "Cancela o processamento" + CRLF + "e abandona a aplicação"
		#DEFINE STR0147 "Processar"
		#DEFINE STR0148 "Cancelar"
	#ENDIF
#ENDIF

