#INCLUDE 'PROTHEUS.CH'
#INCLUDE 'PARMTYPE.CH'

//-----------------------------------------------------------------------
/*/{Protheus.doc} F340BROW()
Ponto de entrada para filtrar os titulos no Browse liberados para compensação 
 
@param		Nenhum
@return		Nenhum
@author 	Zema
@since 		05/09/2017
@version 	1.0
@project	MAN0000001 - Aguassanta - Integra
/*/
//-----------------------------------------------------------------------
USER FUNCTION F340BROW
U_ASFINA69()
RETURN 
