#INCLUDE "TOTVS.CH"
//---------------------------------------------------------------------------------------
/*/{Protheus.doc} CCOME04
Banco de conhecimento - Solicitação de Compras
@author  	Totvs
@since     	01/01/2015
@version  	P.11.8      
@return   	Nenhum 
/*/
//---------------------------------------------------------------------------------------
USER FUNCTION CCOME04(cTipo) 

// Rotina generica - Tratar por tipo 
// No campo tipo será passado como parametro o alias ex: SC1

RETURN