USE ADV_CIEE
GO
IF Exists ( SELECT name FROM sysobjects WHERE name = 'sp_cry01_01' AND type = 'P')
	DROP PROCEDURE sp_cry01_01
GO

/*
------------------------------------------------------------------------------------------------------------
ANALISTA 	JOAO MARCELO SELLEIRO
EMPRESA  	MICROSIGA SOFTWARE
DEPARTAMENTO	BUSINESS INTELLIGENCE
------------------------------------------------------------------------------------------------------------
*/

CREATE PROCEDURE sp_cry01_01 (
	@PAR_FILIAL	CHAR(2),
	@PAR_NUMDE   	CHAR(6),
	@PAR_NUMATE   	CHAR(6),
	@PAR_VIA1	CHAR(2),
	@PAR_VIA2	CHAR(2),
	@PAR_VIA3	CHAR(2),
	@PAR_VIA4	CHAR(2),
	@PAR_USADO	CHAR(1)
)
AS
BEGIN

	SET ANSI_WARNINGS  	OFF
	SET ARITHABORT		OFF
	SET NOCOUNT		OFF

	SELECT 
	C7_FILIAL,
	C7_NUM,
	SX5_Z2.X5_DESCRI,
	C7_FORNECE,
	A2_NOME,
	A2_END,
	A2_BAIRRO,
	A2_MUN,
	A2_EST,
	A2_CEP,
	A2_TEL,
	A2_FAX,
	A2_CONTATO,
	CONVERT(DATETIME,C7_EMISSAO) C7_EMISSAO,
	C7_ITEM,
	C7_PRODUTO,
	B1_DESC,
	COALESCE(CONVERT(TEXT, CONVERT(VARCHAR(8000), CONVERT(VARBINARY(8000), B1_ESPEC))),'') B1_ESPEC,
	C7_QUANT,
	C7_UM,
	C7_PRECO,
	C7_TOTAL,
	C7_NUMSC,
	C7_DESC,
	C7_VLDESC,
	CONVERT(DATETIME,C7_DATPRF) C7_DATPRF,
	C7_CC,
	C7_COND,
	COALESCE(E4_DESCRI, '') E4_DESCRI,
	COALESCE(ZH_PESSOA1, '') ZH_PESSOA1,
	COALESCE(ZH_PESSOA2, '') ZH_PESSOA2,
	COALESCE(ZH_PESSOA3, '') ZH_PESSOA3,
	COALESCE(ZH_PESSOA4, '') ZH_PESSOA4,
	COALESCE(ZH_PESSOA5, '') ZH_PESSOA5,
	COALESCE(ZH_LOCAL, '') ZH_LOCAL,
	COALESCE(CONVERT(TEXT, CONVERT(VARCHAR(8000), CONVERT(VARBINARY(8000), ZH_OBS))),'') ZH_OBS


	FROM SC7010 SC7
	           JOIN SB1010 SB1    ON (B1_FILIAL = C7_FILIAL AND B1_COD = C7_PRODUTO AND SB1.D_E_L_E_T_ = ' ')
	           JOIN SA2010 SA2    ON (A2_FILIAL = '  '      AND A2_COD = C7_FORNECE AND A2_LOJA = C7_LOJA AND SA2.D_E_L_E_T_ = ' ')
	LEFT OUTER JOIN SE4010 SE4    ON (E4_FILIAL = C7_FILIAL AND E4_CODIGO = C7_COND AND SE4.D_E_L_E_T_ = ' ')
	LEFT OUTER JOIN SZH010 SZH    ON (ZH_FILIAL = C7_FILIAL AND ZH_NUM    = C7_NUM  AND SZH.D_E_L_E_T_ = ' ')
		   JOIN SX5010 SX5_Z2 ON (SX5_Z2.X5_TABELA = 'Z2' AND LEFT(SX5_Z2.X5_CHAVE,2) IN (@PAR_VIA1,@PAR_VIA2,@PAR_VIA3,@PAR_VIA4) AND SX5_Z2.D_E_L_E_T_ = ' ')
	WHERE 	C7_FILIAL = @PAR_FILIAL
	AND	C7_NUM = @PAR_NUMDE                  
	AND	SC7.D_E_L_E_T_ = ' '
	ORDER BY 
	C7_FILIAL,
	C7_NUM,
	SX5_Z2.X5_DESCRI,
	C7_ITEM

END

GO
GRANT EXECUTE ON sp_cry01_01 TO dbo


EXEC sp_cry01_01 '01','001974','001974','01','02','03','04','S'







