#include "TOTVS.CH"  
//---------------------------------------------------------------------------------------
/*/{Protheus.doc} CFINA03
Cadastro de CNI - Identificacao
@author     Andy
@since     	01/08/2014
@version  	P.11      
@return    	Nenhum
@obs        Nenhum
Alterações Realizadas desde a Estruturação Inicial
------------+-----------------+----------------------------------------------------------
Data       	|Desenvolvedor    |Motivo                                                                                                                 
------------+-----------------+----------------------------------------------------------
01/09/2014	|Carlos Henrique  | Padronização do fonte para projeto de revitalização 
------------+-----------------+----------------------------------------------------------
/*/
//---------------------------------------------------------------------------------------
User Function CFINA03()
	AxCadastro("SZB", "CNI - Identificacao")
Return  