#Include 'Protheus.ch'

//PONTO DE ENTRADA
//AINDA NÃO FOI COMPILADO
//PROGRAMA PARA TENTAR CARREGAR A DESCRIÇÃO COMPLETA DO PRODUTO DA TABELA SCP SOLICITAÇÃO AO ARMAZEM
// CARREGANDO AUTOMATICAMENTE APOS A BAIXA DA PRE-REQUISIÇÃO

User Function MT241CAB()

_aTstArray := PARAMIXB


Return(_aTstArray)

