#INCLUDE "TOTVS.CH"
//---------------------------------------------------------------------------------------
/*/{Protheus.doc} M020INC
Ponto de entrada após incluir o registro do Fornecedor
@author  	Totvs
@since     	01/01/2015
@version  	P.11.8      
@return   	Nenhum 
/*/
//---------------------------------------------------------------------------------------
USER FUNCTION M020INC()
	
	U_CCOME05(.t.)

RETURN 