#INCLUDE "TOTVS.CH"
//---------------------------------------------------------------------------------------
/*/{Protheus.doc} M020ALT
Ponto de entrada após alterar o registro do Fornecedor
@author  	Totvs
@since     	01/01/2015
@version  	P.11.8      
@return   	Nenhum 
/*/
//---------------------------------------------------------------------------------------
USER FUNCTION M020ALT()
	
	U_CCOME05(.t.)

RETURN 