#include "Protheus.ch"
//---------------------------------------------------------------------------------------
/*/{Protheus.doc} CN140CAN
Sempre que inicia nova Revisão , faz a verificação de contratos de mesmo índice.   
Controle de variavel Static.
@author  	Totvs
@since     	01/01/2015
@version  	P.11.8      
@return   	Nenhum 
/*/
//---------------------------------------------------------------------------------------
User Function CN140CAN()
	U_C8E02SET()// Em CGCTE02.prw
Return